export enum ErrorCodes {
    WEATHER_API_VALIDATION_ERROR = 'WEATHER_API_VALIDATION_ERROR',
    WEATHER_DATA_NOT_FOUND = 'WEATHER_DATA_NOT_FOUND',
    WEATHER_API_TIMEOUT = 'WEATHER_API_TIMEOUT',
    WEATHER_API_ERROR = 'WEATHER_API_ERROR',
    WEATHER_API_GATEWAY_ERROR = 'WEATHER_API_GATEWAY_ERROR',
    CONFIGURATION_ERROR = 'CONFIGURATION_ERROR',
    MISSING_ENV_VARIABLE = 'MISSING_ENV_VARIABLE',
    INVALID_ENV_VARIABLE = 'INVALID_ENV_VARIABLE',
    INVALID_LATITUDE = 'INVALID_LATITUDE',
    INVALID_LONGITUDE = 'INVALID_LONGITUDE',
    MISSING_REQUIRED_PARAMETER = 'MISSING_REQUIRED_PARAMETER',
    INVALID_SUNSHINE_DURATION = 'INVALID_SUNSHINE_DURATION',
    EMPTY_DATA_SET = 'EMPTY_DATA_SET',
    INVALID_WEATHER_CODE = 'INVALID_WEATHER_CODE'
}