name: Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
      - run: npm install
      - run: npm run test:cov
      - run: npm run test:e2e